export default [
    {
        title:'Shell',
        key:'shell',
        clients:[
            {
                title:'cURL',
                key:'curl'
            },
            {
                title:'HTTPie',
                key:'httpie'
            },
            {
                title:'Wget',
                key:'wget'
            }
        ]
    },
    {
        title:'Go Lang',
        key:'go',
        clients:[
            {
                title:'http',
                key:'native'
            }
        ]
    },
    {
        title:'Java',
        key:'java',
        clients:[
            {
                title:'Unirest',
                key:'unirest'
            },
            {
                title:'OkHttp',
                key:'okhttp'
            }
        ]
    },
    {
        title:'JavaScript',
        key:'javascript',
        clients:[
            {
                title:'jQuery',
                key:'jquery.ajax'
            },
            {
                title:'XMLHttpRequest',
                key:'xmlhttprequest'
            }
        ]
    },
    {
        title:'Node.js',
        key:'node.js',
        clients:[
            {
                title:'HTTP',
                key:'native'
            },
            {
                title:'Request',
                key:'request'
            },
            {
                title:'Unirest',
                key:'unirest'
            }
        ]
    },
    {
        title:'Objective-C',
        key:'objective-c',
        clients:[
            {
                title:'NSURLSession',
                key:'nsurlsession'
            }
        ]
    },
    {
        title:'OCaml',
        key:'ocaml',
        clients:[
            {
                title:'CoHTTP',
                key:'cohttp'
            }
        ]
    },
    {
        title:'PHP',
        key:'php',
        clients:[
            {
                title:'PHP Curl',
                key:'ext-curl'
            },
            {
                title:'PECL/HTTP v1',
                key:'pecl/httpv1'
            },
            {
                title:'PECL/HTTP v2',
                key:'pecl/httpv2'
            }
        ]
    },
    {
        title:'Python',
        key:'python',
        clients:[
            {
                title:'Python 3',
                key:'python3'
            },
            {
                title:'Requests',
                key:'requests'
            },
        ]
    },
    {
        title:'Ruby',
        key:'ruby',
        clients:[
            {
                title:'Native',
                key:'native'
            },
       ]
    },
    {
        title:'Swift',
        key:'swift',
        clients:[
            {
                title:'NSURLSession',
                key:'nsurlsession'
            },
        ]
    },
    {
        title:'C#',
        key:'C**#**',
        clients:[
            {
                title:'RestSharp',
                key:'restsharp'
            },
        ]
    },
    {
        title:'C',
        key:'c',
        clients:[
            {
                title:'LibCurl',
                key:'libcurl'
            },
        ]
    },
]
